### ISSUE TITLE
No module named 'runner'

### ISSUE THREAD

**Issue by rongeasy** [Xilinx/DPU-PYNQ#16]
PYNQ V2.5 on Ultra96V2. Follow the steps in README. In last step to build up notebook.

pynq get-notebooks pynq-dpu -p .

root@pynq:/home/xilinx/jupyter_notebooks# pynq get-notebooks pynq-dpu -p .
Delivering notebooks './pynq-dpu'...
Traceback (most recent call last):
  File "/usr/local/bin/pynq-get-notebooks", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pynq/_cli/get_notebooks.py", line 240, in main
    raise e
  File "/usr/local/lib/python3.6/dist-packages/pynq/_cli/get_notebooks.py", line 209, in main
    ext_mod = ext.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/pynq_dpu/__init__.py", line 17, in <module>
    from .dpu import DpuOverlay
  File "/usr/local/lib/python3.6/dist-packages/pynq_dpu/dpu.py", line 20, in <module>
    import runner
ModuleNotFoundError: No module named 'runner'

There is no module named 'runner' on pypi .  Only have one module named "Runner"

**Comment by yunqu** [comment]
This might mean the vart library has not been installed properly. Not sure what happened but you may want to try reinstall dpu-pynq.
